obj-$(CONFIG_POWER_AVS)		+= avs/
obj-$(CONFIG_POWER_RESET)	+= reset/
obj-$(CONFIG_POWER_SUPPLY)	+= supply/
obj-$(CONFIG_OPLUS_SM7250R_CHARGER)	+= oplus/
obj-$(CONFIG_OPLUS_SM8250_CHARGER)	+= oplus/
#endif
